[package]
name = "AAAAAAAAA"
version = "1.0.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"

[dev-dependencies]
unicode-segmentation = "1.12.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false
